language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
 - phpenv config-add test/phpconfig.ini
 - printf "\n\n\n" | pecl install -f pecl_http-1.7.6

script:
 - phpunit --configuration test/phpunit.xml


matrix:
  fast_finish: true

