language: php
dist: trusty
sudo: required

env:
 - PECL_HTTP_VERSION=3.1.1RC1

php:
  - 7.2
  - 7.1
  - 7.0

before_install:
  - composer install --dev
  - sh -c "mkdir -p ${TRAVIS_BUILD_DIR}/travis/module-cache/`php-config --vernum`"
  - sudo apt-get install unzip p7zip-full libgnutls-dev

before_script:
 - ./test/travis/php-modules-install.sh

script:
 - vendor/bin/phpunit --configuration test/phpunit.xml

cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/travis/module-cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: PECL_HTTP_VERSION=2.6.0

